language: python
python:
  - 3.8.2

script:
  - pip install -r requirements.txt
  - python -m unittest -v department_app/tests/test_service_employee.py
  - python -m unittest -v department_app/tests/test_service_department.py
  - python -m unittest -v department_app/tests/test_rest_employee.py
  - python -m unittest -v department_app/tests/test_rest_department.py
  - python -m unittest -v department_app/tests/test_view_employee.py
  - python -m unittest -v department_app/tests/test_view_department.py
  - python -m unittest -v department_app/tests/test_models_employee.py
  - python -m unittest -v department_app/tests/test_models_department.py

after_success:
  - coveralls