language: python
os: windows
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - pylint department_app
  - coverage run -m unittest discover department_app/tests
  - coverage report

after_success:
  - coveralls
